name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: ./test.sh
    
    - name: Update readme according to Go doc
      uses: posener/goreadme@v1
      with:
        readme-file: DOCS.md
        constants: true
        variabless: true
        functions: true
        types: true
        factories: true
        methods: true
        recursive: true
        debug: true
        GITHUB_TOKEN: '${{ secrets.GOQ_CI_GITHUB_TOKEN }}'
      
    - name: Conventional Changelog Action
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: ${{ secrets.GOQ_CI_GITHUB_TOKEN }}
        git-message: 'chore(release): {version}'
        tag-prefix: 'v'
        output-file: 'CHANGELOG.md'

